README.md, package-lock.json
This pull request adds simple installation instructions for those wanting to consume or contribute to the project. The items covered in the installation instructions include.
1. Forking and Cloning the repository.
2. Navigating to the project directory. 
3. Installing the project using `npm i` and `npm install` 
4. Running the installed Node Express server.
5. Feeding back when the server is `Listening` on ports `3000` and `3001`
=> Simple github-proxy Installation Instructions

README.md, lib/config.js, package-lock.json, user-settings.json
This pull request directly relates to #7 that needs local developer configuration enabled in order to test the proxy from forked repos without affecting the deployed proxy.
Within `config.js` the following update was added to override `config.json` if `user-settings.json` exists in the project root.
* The default configuration is `config.js`.
* If `user-settings.json` exists in the `project root` and the value `repoWhiteList` exists as `json`, then `user-settings.json` settings override `config.js`
```
let _userSettings = null;
const userSettings = () => {
const path = './user-settings.json';
if (_userSettings === null && fs.existsSync(path)) {
_userSettings = JSON.parse(fs.readFileSync(path));
}
return _userSettings;
};
let _whiteList = proxySettings.repoWhiteList;
const getWhiteList = …
```
=> Configuration of local developer environment and updated user instructions

README.md, server/package.json, server/resources/config.json, ui/package.json
We can merge this PR right before the code transfer.
=> Setting npm scope to @finos

SECURITY.md
Adds a simple security policy to the project with an e-mail address as point-of-contact.
=> Create a security policy for the project

SECURITY.md
Add opensource@citi.com to `SECURITY.md` for repository [security policy](https://github.com/finos/git-proxy/security/policy).
=> Update security policy with new e-mail

package-lock.json, package.json, src/ui/layouts/Admin.js
=> Remove perfect-scrollbar as dependency

website/docusaurus.config.js, website/sidebars.js, website/src/components/feature-config.js, website/src/components/feature.js, website/src/pages/index.js
=> fix: lint errors for website branch fix

website/src/components/feature.js
=> fix: add PropTypes import

package-lock.json, package.json
Address pipeline breakage for CVE Scanning for Node.js action 👍
=> Address CVE scan pipeline breakage on axios

.github/workflows/cve-scanning-node.yml, .github/workflows/license-validation.yml, .github/workflows/nodejs.yml, .github/workflows/npm.yml, package-lock.json
=> Bump CI Node to 18.x + address `follow-redirects` vulnerability & failing CI

README.md
Working on #365 
@rgmz - would you mind reviewing these changes an provide feedback?
Thanks!
=> Improve README "About" description & add Mermaid diagram

.github/workflows/codeql.yml
Trying to address CodeQL issue `CodeQL analyses from advanced configurations cannot be processed when the default setup is enabled` on #403
=> Create codeql.yml GitHub Action

src/proxy/routes/index.js, src/ui/components/Snackbar/Snackbar.jsx, test/testProxyRoute.js
Includes various touch ups for complaints from ESLINT and Prettier.
=> fix: address ESLINT and Prettier complaints

website/src/pages/index.js
As per Slack conversation, adding my details to the website
=> docs:  add Miklos details to git-proxy.finos.org

.github/workflows/dependency-review.yml, website/package.json
=> Revert "Remove development run time from `fail-on-scope` (Dependency Review) ✅ "

.github/workflows/release.yml
ref: https://finos-lf.slack.com/archives/C06LXNW0W76/p1715350005144639?thread_ts=1715346130.935009&cid=C06LXNW0W76
=> ci(fix): Limit when the releaser is run

.github/release-drafter.yml
Small improvements to the GitHub release markdown to be consistent with previous releases. Also adjustment to the release title for consistency too 👍
=> chore(ci): update template name and github release markdown format

package-lock.json, package.json
=> chore(release): v1.2.3

package-lock.json, package.json
=> chore: v1.3.1 🎉 

package-lock.json, package.json
=> chore: v1.3.2

CODE_OF_CONDUCT.md, CONTRIBUTING.md, certs/create-cert.sh, config.schema.json, index.html, packages/git-proxy-cli/index.js, packages/git-proxy-cli/package.json, packages/git-proxy-cli/test/testCliUtils.js, scripts/doc-schema.js, src/plugin.js, src/proxy/processors/push-action/blockForAuth.js, src/ui/components/Footer/Footer.jsx
=> chore: propagate renaming to remaining files

website/docusaurus.config.js, website/package.json, website/src/pages/index.js, website/yarn.lock
=> chore: add all maintainers & contributors to docs site ❇️ 

README.md
@JamieSlome - should we also add something on git-proxy.finos.org ?
=> docs: adding Zoom meeting and mailing list to README

package-lock.json, package.json
Prepare release for `v1.3.3` 👍
=> chore: v1.3.3

package-lock.json, package.json
=> chore: v1.3.4

package-lock.json, package.json
=> fix: resolve build error on arm64 machine

package-lock.json, package.json
Prepares release of `v1.3.5` 👍
=> chore: bump minor to v1.3.5

package-lock.json, package.json
=> chore: bump minor to v1.3.6

package-lock.json, package.json
=> chore: bump minor to v1.3.7

package-lock.json, package.json
=> chore: bump minor to v1.3.8

package-lock.json, package.json
=> chore: bump patch version to 1.3.9

package-lock.json, package.json
Prepare release of `v1.3.10` 👍
=> chore: bump patch version to 1.3.10

package-lock.json, package.json
=> chore: bump minor for release v1.4.0

package-lock.json, package.json
=> chore: bump patch to 1.4.1

package-lock.json, package.json
=> chore: bump minor to 1.5.0

src/proxy/processors/push-action/blockForAuth.js, src/service/routes/repo.js, src/service/urls.js, test/proxyURL.test.js
Now we can override the domains used by the service and proxy
the auth processor needs to use those values
=> fix: adjust auth processor to use custom service url

package.json
**This PR updates the start script in package.json to ensure cross-platform compatibility by modifying the command syntax. The change addresses potential issues on different operating systems when running npm run server and npm run client concurrently.**
The _**start**_ script was modified from single quotes to double quotes to make it compatible across Windows, macOS, and Linux environments:
`"start": "concurrently 'npm run server' 'npm run client'",`
_was updated to:_
`"start": "concurrently \"npm run server\" \"npm run client\"",`
- Single quotes in scripts can cause issues on Windows systems, as they are interpreted differently. Using double quotes ensures that the command runs consistently on all platforms.
- This change improves the reliability of the development workflow by …
=> fix: update server start script for cross-platform compatibility

package-lock.json, package.json
=> chore: version bump patch to 1.5.1

package-lock.json, package.json
=> chore: version bump patch to v1.5.2

package-lock.json
Fix sync issue between `package.json` and `package-lock.json` 👍
=> fix: sync issue between dependency manifest in package-lock.json and package.json

package-lock.json, package.json
=> chore: bump minor version to 1.6.0

package-lock.json, package.json
=> chore: bump version by minor to v1.7.0

package-lock.json, package.json
=> chore: bump version by patch to v1.7.1

src/proxy/index.js, src/service/index.js
- **refactor: allow for extending express**
=> refactor: allow for extending express

package-lock.json, package.json
Prepares release of `v1.8.1` 👍
=> chore: bump by patch to 1.8.1

package-lock.json, package.json
=> chore: bump by minor to 1.9.0

package-lock.json, package.json
=> chore: bump by patch to 1.9.1

package-lock.json, package.json
=> chore: bump by patch to 1.9.2

package-lock.json, package.json
=> chore: bump by minor to 1.9.3

src/ui/views/OpenPushRequests/components/PushesTable.jsx
The Dashboard section was no longer displaying push data after merging search and pagination (https://github.com/finos/git-proxy/pull/804)
=> fix: dashboard not displaying push data

package-lock.json, package.json
Run of `npm audit fix --force` 👍
=> chore: run npm audit fix

package-lock.json, package.json
Prepare release of `v1.11.0` 👍
=> chore: bump by minor to v1.11.0

package-lock.json, package.json
Prepare release of `v1.12.0` 👍
=> chore: bump by minor to v1.12.0

package-lock.json, package.json
Prepare release of `v1.13.0` 👍
=> chore: bump by minor to v1.13.0

package-lock.json, package.json
Prepare release of `v1.14.0` 👍
=> chore: bump by minor to v1.14.0

package-lock.json, package.json
Prepare release of `v1.15.0` 👍
=> chore: bump by minor to v1.15.0

package-lock.json, package.json
Prepare release of `v1.16.0` 👍
=> chore: bump by minor to v1.16.0

package-lock.json, package.json
Prepare release of `v1.17.0` 👍
=> chore: bump by minor to v1.17.0

package-lock.json, package.json
Prepare release of `v1.17.2` 👍
=> chore: bump by patch to v1.17.2

README.md
replace incubating with active badge
=> chore: apply finos active badge

package-lock.json, package.json
Prepare release of `v1.19.0` 👍
=> chore: bump by minor to v1.19.0

index.ts, src/config/index.ts, test/testActiveDirectoryAuth.test.js, test/testAuthMethods.test.js, test/testConfig.test.js
=> fix: restore user configs being merged with defaults

.github/workflows/npm.yml
Fixes #1151.
Validating this requires making a release so I'm not 100% sure if it's good to go.
Pinging @kriswest for a quick look!
=> chore: update npm release workflow to handle pre-releases
