finos/git-proxy

README.md

Update README.md - When you clone a project you should use port 8000 instead of 3000

Update README.md - When you clone a project you should use port 8000 instead of 3000

---

package-lock.json

Don't think it's needed, and scanning tools get confused by it.

Deleted package-lock.json at root level

---

package.json

See https://github.com/facebook/create-react-app/issues/2696
There are probably few others, we should move as much as possible into devDependency, to keep the runtime leaner.

react-script should be a devDependency

---

README.md

One-letter fix: `repositor` > `repository`

Fixes README.md typo for "repository"

---

.github/workflows/license-validation.yml
.github/workflows/nodejs.yml
README.md
package-lock.json
package.json

fix: updates workflows to run on `main` (the default branch) instead of `master`, and installs `mocha` as a `devDependency` inside the project instead of requiring a global installation so that `npm test` works "out of the box" on developer workstations

fixes workflows

---

.github/workflows/npm.yml

When publishing a scoped package for the first time, the following must be set:
```bash
npm publish --access=public
```
The following run failed due to the lack of the `--access` flag:
https://github.com/finos/git-proxy/actions/runs/5394794276

Set NPM publish to public access for initial release

---

.commitlintrc.json
.husky/commit-msg
commitlint.config.js
package-lock.json
package.json

feat: introduce proper commit linting

---

package-lock.json
package.json

Introduced a preinstall hook that ensures that [husky](https://typicode.github.io/husky/) is installed after a npm install.
Checks for proper commit messages should pass properly after this.

fix: commit lint bug

---

package.json
scripts/prepare.js

Fix #188
Verified by running ```npm run prepare``` that files in .husky are created from the script as they currently are.
Should we remove the preinstall script too @JamieSlome

fix: add prepare hook for husky install

---

index.html
package-lock.json
package.json
vite.config.js

Fix #192
Notes:
1. Removed react-scripts from package.json scripts. Left the eject script as it is. Let me know if it has to be removed.
2. Moved the index.html file from public to root folder. Updated the URLs and added index.js in script.
3. Added vite config file.
Verified that it works by running vite start.
Issues:
Currently on running the server, getting this warning in console:
```(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.```
Let me know if you would like to be fixed or we can leave it.
@JamieSlome

feat: add vite and remove react-scripts

---

package-lock.json
src/index.js
src/ui/layouts/Admin.js
src/ui/views/Dashboard/Components/PushTable.js
src/ui/views/Login/Login.js
src/ui/views/OpenPushRequests/components/PushesTable.js
src/ui/views/PushDetails/PushDetails.js
src/ui/views/RepoDetails/Components/AddUser.js
src/ui/views/RepoDetails/RepoDetails.js
src/ui/views/RepoList/Components/Repositories.js
src/ui/views/User/User.js
src/ui/views/UserList/Components/UserList.js

Fix breakages caused by migration to latest `react-router-dom@6.14.1`

---

.husky/commit-msg

Closes #241 
@JamieSlome Tested and verified on local by creating linting issues and then trying to commit. This fixes any auto fixable issues and doesn't allow the commit to go through if it can't fix them all. User can see the errors in the ```Command Output``` as well in the ```Problems``` console where it would be highlighted already.
As for the separate ```.prettierrc``` file that we had discussed, we don't really need this one here as we are already using ```eslint-plugin-prettier``` and ```eslint-config-prettier``` which essentially combine eslint with prettier to work together and work to avoid any conflicts. In case any conflicts still come up or specific customisation is needed, they are defined in the rules object in the ```eslintrc.cjs``` file. For more details, you can refer …

fix: add pre-commit lint hook to husky

---

src/index.jsx
src/ui/layouts/Admin.jsx
src/ui/views/Login/Login.jsx
src/ui/views/PushDetails/PushDetails.jsx
src/ui/views/User/User.jsx

preface: not well versed in front-end or React. Tidying up a series of errors seen when pulling up the ui. A follow-up from #185 
- fix redirect from `/login` to `/admin` on submit. It would dump you back to the main login page and wouldnt redirect.
- fix below error when loading `/admin` by replacing `<Navigate />` with a `<Route ...element={<Navigate />} />` component:
```
Uncaught Error: [Navigate] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>
```
- make parent route /admin/* so children are routed correctly:
```
You rendered descendant <Routes> (or called `useRoutes()`) at "/admin" (under <Route path="/admin">) but the parent route path has no trailing "*". This means if you navigate deeper, the parent won't match anymore and …
```

fix: cleanup deprecated behaviour from react-router

---

netlify.toml

Add `netlify.toml` with build base directory specified

---

src/config/env.js
src/proxy/index.js
src/proxy/processors/push-action/blockForAuth.js
src/service/index.js
src/ui/services/git-push.js
src/ui/services/repo.js
src/ui/services/user.js
src/ui/views/Login/Login.jsx
test/testConfig.js
website/docs/configuration/overview.mdx

Closes #378 
To test this PR:
```
npm install -g
export GIT_PROXY_UI_PORT="5000"
export GIT_PROXY_SERVER_PORT="9090"
git-proxy
```
You should see:
```
Service Listening on 5000
Listening on 9090
```

feat: allow ports to be customised via env vars

---

README.md

Closes #436
---
@msagi, did I miss anything?

Addresses #436 and corrects configuration docs link

---

.github/workflows/nodejs.yml
src/db/index.js

fix: use codecov for test coverage reports

---

.github/workflows/nodejs.yml
README.md
codecov.yml
nyc.config.js

Fixes #441 
- codecov-action@v4 requires the token to be set
- flags are not necessary at this time. its [used to differentiate](https://docs.codecov.com/docs/flags) test types and/or sub-components in a monorepo. For now, we just want to see all test coverage across the whole project.

fix(ci): set CODECOV_TOKEN after action upgrade

---

src/proxy/index.js
src/proxy/routes/index.js
test/testRouteFilter.js

Fixes #410 
(Hello from Git Proxy 👋)

feat: http filtering

---

package-lock.json

Addresses CVE-2023-42282 in `package-lock.json` failing CVE Scanning workflow 👍

Address IP vulnerability (CVE-2023-42282) via `npm audit fix` ❤️ 

---

index.js

Fixes #473 .
Any command-line argument given that is not demanded, or does not have a corresponding description, will be reported as an error. This helps to avoid issues with command line arguments having typos, e.g. --configg 
Correct command line arguments: no change in behaviour
```
git-proxy --config my-config.json 
Listening on 8000
Service Listening on 8080
```
Typo in command line argument: error message printed
``` 
git-proxy --configg my-config.json
Usage: git-proxy [options]
Options:
--help      Show help                                            [boolean]
--version   Show version number                                  [boolean]
-v, --validate  Check the proxy.config.json file in the current working
directory for validation errors.
-c, --config    Path to custom git-proxy …
```

feat: print error message for unknown argument

---

package-lock.json
package.json
src/service/index.js

Remove CSRF due to login breakage

---

.github/workflows/nodejs.yml
package.json

Currently failing tests are not reported to the CI pipeline resulting in pull requests being merged even when tests are failing 👍

Report on coverage only and block CI on tests failure #495

---

.github/workflows/dependency-review.yml
website/package.json

Remove development run time from `fail-on-scope` (Dependency Review) ✅ 

---

.github/workflows/dependency-review.yml

Add `caniuse-lite` to `allow-dependencies-licenses` for Dependency Review

---

packages/git-proxy-cli/index.js
packages/git-proxy-cli/test/testCli.test.js
packages/git-proxy-cli/test/testCliUtils.js
src/service/routes/push.js

Updated the git-proxy-cli tests to track development on reconcile branch

Fix git-proxy-cli tests

---

package.json
website/docs/installation.mdx
website/docusaurus.config.js

Updates library version to `1.2.0` 👍

Update version from `1.1.0` to `1.2.0`

---

src/proxy/chain.js
src/proxy/processors/push-action/clearBareClone.js
src/proxy/processors/push-action/index.js
test/testClearBareClone.test.js

Remove local `.remote` folders once access is no longer required

---

package.json
src/proxy/processors/push-action/pullRemote.js
website/docs/installation.mdx
website/docusaurus.config.js

Removes the usage of auth headers for shallow clones of upstream repositories for diff generation.

Remove auth headers from bare git clone on server

---

.github/workflows/release.yml

This condition wasn't behaving as expected, removing.
Relates to #532

ci(fix): Remove NPM step condition

---

.github/workflows/release.yml

Include `package.json` and `package-lock.json` as included paths for automated releases. This primarily addresses dependency updates introduced by Renovate bot.

chore(ci): update release.yml paths to include package.json and package-lock.json

---

.github/workflows/release.yml

Disabling auto release until #557 has been implemented. #557 is required to ensure that the contents of a tag and release don't fall out of sync with the version reflected in the `package.json` and `package-lock.json`.
@eddie-knight, I know we can bump the version using `npm version major | minor | patch` however don't know from our workflow how to calculate whether the release is major, minor or patch. Any ideas from your implementation?

chore(ci): disable auto release until auto version bumping implemented

---

.github/workflows/npm.yml

Including the build step would integrate the frontend build into the package on the npm registry, which should resolve the UI error that occurs when users follow the installation instructions.

chore: add npm run build step to CI workflow

---

website/README.md
website/docs/installation.mdx
website/docs/quickstart/approve.mdx
website/docs/usage.mdx
website/docusaurus.config.js

Aligns docs with use of UI + minor typo touchups 👍

chore(docs): typos and documentation adjustments

---

README.md
website/package.json
website/src/pages/index.js
website/yarn.lock

chore: add demo video to docs site and README

---

website/docs/installation.mdx

Found these instructions helpful when testing PRs

docs: install a local checkout

---

.github/workflows/scorecard.yml
README.md

Enabling OpenSSF Scorecard  would help git-proxy project improve its security practices and help consumers evaluate the safety of their dependencies.
Fixes #675

chore: create scorecard.yml

---

website/docusaurus.config.js
website/package.json

FINOS marketing team would like to add Google Analytics to https://git-proxy.finos.org/

feat: add google analytics docusaurus plugin

---

package-lock.json
package.json
src/db/index.js
src/service/passport/local.js
test/testUserCreation.test.js

Removes dependency on node-gyp built extensions. Pure JS.
There could be slight performance penalty but makes the project more portable.

chore: move from bcrypt to bcryptjs

---

src/ui/views/RepoList/Components/RepoOverview.jsx

closes #669 
Instead of getting the origin from the vite environment variables, the component will now get the origin from browsers 
JavaScript location API and It won't show undefined in the server

fix: #669-ui/docs: clone component is undefined when running as a server

---

src/config/index.js

Currently most config options can be replaced, this change adjusts the rest
to also allow for this.

fix: allow all default config to be replaced by user config

---

package.json
packages/git-proxy-cli/package.json
packages/git-proxy-notify-hello/package.json

Add 'repository' field [1] to various package.json to create a link between release artifacts and corresponding code in the project's repository. This helps SBOM tools such as ORT [2] to create better SBOMs and reduces amount of code that needs to scanned and reviewed for license compliance.
[1]: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository
[2]: https://github.com/oss-review-toolkit/ort
Bit of context: I am working on generating high quality SBOM (e.g with licenses clarified till file level) for eventually all FINOS projects so they can be easier adopted and used in high compliance environments where SBOMs are or will be a  "must-have". Don't want to burden maintainers with what's a FOSS consumer topic imo so went I see things causing SBOM issue you will see me …

chore: Add repository in package.json files

---

src/db/mongo/users.js
src/service/routes/auth.js
test/testLogin.test.js

Remove all places where passwords are returned in user objects or logged to console

chore: dont leak password from server

---

src/proxy/processors/push-action/pullRemote.js

When `pullRemote.js` is imported for the first time, the `.remote` folder is created. At the end of the chain the `clearBareClone.js` function purges the `.remote` folder. This change ensures that the `.remote` folder can be re-created on subsequent pushes by introducing the `mkdirSync()` call into the `exec()` function which is exported and called in the chain 👍

fix: move creation of remote folder into function call

---

src/proxy/processors/push-action/pullRemote.js

This PR modifies the directory creation permissions in the pullRemote function of pullRemote.js. 
Previously, the function was setting directory permissions to 0777 (full read, write, and execute permissions for user, group, and others). This approach is not aligned with best practices for security, particularly in secure environments such as OpenShift, where overly permissive settings can lead to vulnerabilities.
The updated code now sets the permissions to 0755 (read, write, and execute for the user; read and execute for group and others). This change enhances security by restricting write access to the owner only while still allowing necessary read and execute permissions.

fix: Update pullRemote.js to set appropriate directory permissions

---

package.json
plugins/git-proxy-plugin-samples/example.cjs
plugins/git-proxy-plugin-samples/index.js
test/fixtures/test-package/default-export.js
test/fixtures/test-package/multiple-export.js
test/fixtures/test-package/package.json
test/fixtures/test-package/subclass.js
website/docs/development/plugins.mdx

Exports makes it hard to access other paths in the project
Until we arrive on stable interfaces to access other parts of git-proxy
removing exports would be helpful.
Import paths have been adjusted slightly for plugins and the docs for
plugins due to the exports aliases being a bit different.

refactor: remove exports from package.json and adjust imports

---

experimental/license-inventory/package-lock.json
experimental/license-inventory/package.json
experimental/license-inventory/src/app.ts
experimental/license-inventory/src/db/connect.ts
experimental/license-inventory/src/db/index.ts
experimental/license-inventory/src/db/schemas/license/license.test.ts
experimental/license-inventory/src/db/schemas/license/license.ts
experimental/license-inventory/src/env.ts
experimental/license-inventory/src/routes/api/index.ts
experimental/license-inventory/src/routes/api/v0/index.ts
experimental/license-inventory/src/routes/api/v0/licenses.test.ts
experimental/license-inventory/src/routes/api/v0/licenses.ts
experimental/license-inventory/src/server.ts
experimental/license-inventory/src/services/data/index.ts
experimental/license-inventory/src/services/data/license.ts
experimental/license-inventory/src/services/data/mongoose/index.ts
experimental/license-inventory/src/test/globalTeardown.ts
experimental/license-inventory/src/test/mock/db.ts
experimental/license-inventory/src/types.ts
experimental/license-inventory/tsconfig.json

Defined a database layer
Added an implementation using mongoose
Refactored the express routes to take an implementation
Added a mockable implementation
Refactored the tests to use the mockable implementation
Added tests for the get by uuid route
---
I'm not huge on OOP so the classes are more similar to go services
This method allows for easier mocking of the DB interactions with correct typechecking.
We also get to ensure we're using the same DB connection everywhere rather than trusting global variables.

refactor(experimental): abstract data layer

---

experimental/license-inventory/package-lock.json
experimental/license-inventory/package.json

Bumps license inventory to `v0.0.2` with latest changes from #854 👍 
(cc) @06kellyjac

chore: bump experimental license inventory to 0.0.2 with #854

---

renovate.json

Grouping smaller updates can speed up maintenance as
we dont have to merge, rebase others, merge, repeat

chore: tweak renovate to reduce pr total

---

test/testClearBareClone.test.js

Hi, this PR fixes the following flaky tests:

fix: clean up .remote folder after tests and extend timeout

---

website/docs/usage.mdx

resolves #724 
Adds a small note to documentation on configuring a web proxy for `npx`

docs: add note on npx proxy configuration

---

.eslintrc.json

Disable `@typescript-eslint/no-explicit-any` warnings due to visual noise in pull requests on GitHub 👍

chore: switch @typescript-eslint/no-explicit-any to off instead of warn

---

README.md

Some small cosmetic fixes in the markdown in the README

docs(readme): fix markdown in README

---

src/proxy/chain.ts
src/proxy/processors/push-action/gitleaks.ts
src/proxy/processors/push-action/index.ts
test/chain.test.js

integrate support for gitleaks checks (default off for now)
Users must make the gitleaks binary available on the PATH for git-proxy and enable via the git-proxy settings

feat: integrate gitleaks

---

.github/ISSUE_TEMPLATE/meeting_minutes.md

add meeting minutes GitHub Issue template

chore: create meeting_minutes.md

---

.gitignore
config.schema.json
package.json
packages/git-proxy-cli/index.js
proxy.config.json
src/config/ConfigLoader.ts
src/config/index.ts
src/proxy/chain.ts
src/proxy/index.ts
src/service/index.js
test/ConfigLoader.test.js
test/chain.test.js
website/docs/configuration/overview.mdx
website/docs/configuration/reference.mdx

This pull request introduces a significant update to the configuration management system of the GitProxy application. The main changes include adding support for multiple configuration sources, implementing a new configuration loader class, and providing the ability to reload configurations without restarting the application.
* Added support for multiple configuration sources in `config.schema.json` and `proxy.config.json`, allowing the configuration to be sourced from files, HTTP endpoints, or Git repositories. [[1]](diffhunk://#diff-be1695b1e63a508d59982601f9e1fb7f58247deecb1e427adb77bcad758ae5e5R8-R19) [[2]](diffhunk://#diff-c465aafa0fe603e2d28b017938f55e5ce3253aac7aa303efeabfc06a4ad52d5fR5-R42)
* Introduced a new `ConfigLoader` class in `src/config/ConfigLoader.js` to manage the …

feat: implements config loader to enable remote or external configs

---

src/service/passport/activeDirectory.js

Could never match any string transformed to lowercase to "activeDirectory"

fix: correct method for finding ad configuration

---

test/ConfigLoader.test.js

resolves #1049 
Clean up after the Config Loader tests by making sure reloads are stopped and the default config is reloaded. This improves (reduces) spurious log output through the rest of the tests.

test: stop the config loader and restore defaults after tests have run

---

.github/workflows/ci.yml
package.json
src/config/ConfigLoader.ts

**fix: correct typing for ConfigLoader env**
Was providing a number which can be coerced to a string but TS is a bit more strict asking for string values for env.
Also swapped 0 to false to be more clear and added a docs link.
**chore: add tsc for just server and add to CI**
Add type checking for the server to CI.
Type Checking for the whole project would be good but the frontend has some typechecking rules which work fine for the build but tsc doesn't currently respect. Will fix in the future.

fix: correct typing for ConfigLoader env

---

src/service/routes/auth.js
test/services/routes/auth.test.js

A recent penetration test identified a security issue in the `/api/v1/auth/gitAccount` endpoint:
- Users can add or update their own GitHub/GitLab account names.
- Admins can add or update GitHub/GitLab account names for any user.
- However, **the API does not enforce this restriction** — any user can change the Git account name for any other user, regardless of their permissions.
The API only checks that the requester is authenticated; it does not verify whether the user is updating their own account or has admin privileges.
This PR introduces a guard clause that ensures the requesting user is either:
- Updating their own Git account
- Has admin privileges.
This change brings the backend access control in line with the intended behaviour already enforced in the UI.
I’ve added a new …

fix: prevent non-admin users changing another user's gitAccount

---

src/db/file/pushes.ts
src/db/helper.ts
src/db/mongo/pushes.ts
src/proxy/processors/push-action/checkRepoInAuthorisedList.ts
src/proxy/processors/push-action/checkUserPushPermission.ts
src/ui/views/OpenPushRequests/components/PushesTable.tsx
src/ui/views/PushDetails/PushDetails.tsx
src/ui/views/RepoDetails/RepoDetails.tsx
test/db-helper.test.js
test/testDb.test.js

Currently .git is being replaced in repoNames but `replace` only catches the first match from left to right
```js
> "hello.gitfrom.git".replace(".git", "")
'hellofrom.git'
```
Git repos can have .git included in the name so to correctly get the repoName without a trailing `.git`
it should only be removed from the back (assuming it's there).
Trailing `.git` being trimmed by github:
`.git` being allowed mid repo-name:
`.git` being allowed at the start of a repo name
This code checks the string ends with `.git`. If it does it returns the string up to but not including `.git`, otherwise it returns the whole string.
I've added a new test just for this edgecase.
- **fix: only trim trailing .git not any match**
- **fix: trim ref/heads/ only from the prefix**
- **test: improve visibility of …

fix: only trim trailing .git not any match

---

SECURITY.md

Clarifies the preferred vulnerability disclosure process by directing users to report via GitHub and linking to the FINOS security vulnerabilities policy.
Closes [1018](https://github.com/finos/git-proxy/issues/1018)

docs: update SECURITY.md with reporting guidance

---

package-lock.json
package.json
test/ConfigLoader.test.js

For the `rc.2` prerelease containing changes in #1043.
Also fixes two failing tests due to a removed config entry.

chore: bump version to rc.2

---

src/types/models.ts
src/ui/utils.tsx
src/ui/views/OpenPushRequests/components/PushesTable.tsx
src/ui/views/PushDetails/PushDetails.tsx

resolves #1175 
Replaces estimated links to git profile URLs on the OpenPushRequests and PushDetails views with mailto: links based on the email addresses used in commits (simple and will be supportable for all SCM providers/bare git servers).
OpenPushRequests was previously only rendering a link for the first author in a push. It will now extract a list of unique authors appearing in the push and render a link for each (one per line, in order of appearance).

fix: render committer and author email links instead of estimated profile links

---

src/db/mongo/users.ts

Updating a user (e.g., adding a GitHub username) currently fails with a MongoDB server exception. The issue arises because the user object already includes an _id, and the update attempt tries to overwrite it:
```
MongoServerError: The _id field cannot be changed
```
* Removes the `_id` property from the user object before updating.
* Performs an update by `_id` if one exists.
* If no `_id` is present, inserts a new user with a no-op filter (`{ username: user.username }`).

fix: "MongoServerError: The _id cannot be changed" when updating users
